# Generated by Django 4.2.1 on 2023-05-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eExamApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_models',
            name='decision_name',
        ),
    ]
