# Generated by Django 4.2.1 on 2023-06-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eExamApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_models',
            name='exam_date',
            field=models.DateField(default='0'),
        ),
        migrations.AlterField(
            model_name='exam_models',
            name='exam_time',
            field=models.TimeField(default='0'),
        ),
    ]
