# Generated by Django 4.2.1 on 2023-06-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eExamApp', '0002_alter_exam_models_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_models',
            name='exam_date',
            field=models.DateField(default='2000-10-1'),
        ),
        migrations.AlterField(
            model_name='exam_models',
            name='exam_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
