# Generated by Django 4.2.1 on 2023-06-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eExamApp', '0003_alter_exam_models_exam_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_models',
            old_name='model_state',
            new_name='model_degree',
        ),
        migrations.RemoveField(
            model_name='exam_models',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam_models',
            name='exam_time',
        ),
        migrations.AddField(
            model_name='exam_models',
            name='exam_dateTime',
            field=models.DateTimeField(default='2000-10-1 00:00:00'),
        ),
    ]
