# Generated by Django 4.2.1 on 2023-06-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eExamApp', '0005_exam_models_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_models',
            name='model_degree',
            field=models.IntegerField(default=60),
        ),
    ]
