# Generated by Django 4.2.1 on 2023-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eExamApp', '0006_alter_exam_models_model_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_models_questions',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
